# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims_fa', '0002_auto_20171106_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'managed': False},
        ),
    ]
