# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_fa', '0003_auto_20171106_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': '测试',
            },
        ),
    ]
